blog/Controllers/PageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Mail;
using blog.Models;
using System.Text;

namespace blog.Controllers
{
    public class PageController : Controller
    {
        
        public ActionResult Index()
        {
            ViewBag.Title = "Home";
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Title = "Contact";
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Title = "About";
            return View("About");
        }
        [HttpPost]
        public ActionResult Contact(blog.Models.ContactModels c)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    MailMessage msg = new MailMessage();
                    SmtpClient smtp = new SmtpClient();
                    MailAddress from = new MailAddress(c.Email.ToString());
                    StringBuilder sb = new StringBuilder();
                    msg.IsBodyHtml = false;
                    smtp.Host = "mail.yourdomain.com";
                    smtp.Port = 25;
                    msg.To.Add("youremail@email.com");
                    msg.From = from;
                    msg.Subject = "Contact Us";
                    sb.Append("First name: " + c.FirstName);
                    sb.Append(Environment.NewLine);
                    sb.Append("Last name: " + c.LastName);
                    sb.Append(Environment.NewLine);
                    sb.Append("Email: " + c.Email);
                    sb.Append(Environment.NewLine);
                    sb.Append("Comments: " + c.Comment);
                    msg.Body = sb.ToString();
                    smtp.Send(msg);
                    msg.Dispose();
                    return View("Success");
                }
                catch (Exception)
                {
                    return View("Error");
                }
            }
            return View();
        }
    }
}

blog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Blog</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="@Request.Url.GetLeftPart(UriPartial.Authority)/Scripts/tinymce/tinymce.min.js"></script>
</head>
<body>
<div id="container">
<header>
    <h1>@Html.ActionLink("My ASP.NET Blog", "Index", "", null, new { @class = "header-title" })</h1>
    <h2>@Html.ActionLink("Tagline", "Index", "", null, new { @class = "header-description" })</h2>
</header>
<nav>
 <ul>
    <li>@Html.ActionLink("Home", "Index", "Page")</li>
    <li>@Html.ActionLink("About", "About", "Page")</li>
    <li>@Html.ActionLink("Blog", "Index", "Blog")</li>
    <li>@Html.ActionLink("Contact", "Contact", "Page")</li>
 </ul>
</nav>
<section>
    @RenderBody()
</section>
       
<footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Blog <div id="login">@Html.Partial("_LoginPartial")</div>
                @if (User.Identity.IsAuthenticated)
                    {
                <a href="@Request.Url.GetLeftPart(UriPartial.Authority)/Blog/Create">Post Article</a>
                   }</p>
</footer>
</div>
</body>
</html>